name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: TRUE
          SHOW_LOC_CHART : TRUE
          SHOW_OS: FALSE
          SHOW_PROFILE_VIEWS: FALSE
          SHOW_TOTAL_CODE_TIME: TRUE
          SHOW_PROJECTS: FALSE
          SHOW_LANGUAGE: TRUE
          SHOW_LINES_OF_CODE: TRUE
          SHOW_TIMEZONE: TRUE
          SHOW_EDITORS: FALSE
          SHOW_DAYS_OF_WEEK: TRUE
          SHOW_SHORT_INFO: TRUE
          SYMBOL_VERSION: 1
